kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: default
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }}
